### ISSUE TITLE
Trailing slash

### ISSUE THREAD

**Issue by dgilge** [lhermann/langify-docs#2]
Does Vue.js or we want trailing slashes in the API URLs?

> Trailing slashes are conventional in Django, but are not used by default in some other frameworks such as Rails. Which style you choose to use is largely a matter of preference, although some javascript frameworks may expect a particular routing style.

http://www.django-rest-framework.org/api-guide/routers/#simplerouter

**Comment by lhermann** [comment]
Vue doesn't care because it does not have any native way of making ajax request. I will use axios, which can be configured however we want. Do let's do it the django way.
