### ISSUE TITLE
Firefox cursor jumping

### ISSUE THREAD

**Issue by dgilge** [lhermann/langify-docs#6]
The cursor jumps to the beginning of the paragraph if it is at the end after typing a whitespace in Firefox. This doesn't happen on https://yabwe.github.io/medium-editor/ It is not associated with `setInterval`, `postDraft` or `requestUpdates` as far as I understand it. `ParagaphEditor` is too complex for me.

The problem does not appear on Chrome or Safari

**That means Firefox is currently not supported.**

**Comment by lhermann** [comment]
Wrong repository for this issue ... :)

**Comment by dgilge** [comment]
I chose this repo because it's a bug users encounter (and might want to find a reason for) and this is our public repo.

**Comment by lhermann** [comment]
Oh, I see. Anyway, I copied it over to the other repo for now. Next time I know.
